/*
 * Error codes mapped from Polymarket CLOB docs.
 */

/**
 * Server error codes returned by the CLOB placement endpoint.
 */
export enum PolymarketErrorCode {
  INVALID_ORDER_MIN_TICK_SIZE = "INVALID_ORDER_MIN_TICK_SIZE",
  INVALID_ORDER_MIN_SIZE = "INVALID_ORDER_MIN_SIZE",
  INVALID_ORDER_DUPLICATED = "INVALID_ORDER_DUPLICATED",
  INVALID_ORDER_NOT_ENOUGH_BALANCE = "INVALID_ORDER_NOT_ENOUGH_BALANCE",
  INVALID_ORDER_EXPIRATION = "INVALID_ORDER_EXPIRATION",
  INVALID_ORDER_ERROR = "INVALID_ORDER_ERROR",
  EXECUTION_ERROR = "EXECUTION_ERROR",
  ORDER_DELAYED = "ORDER_DELAYED",
  DELAYING_ORDER_ERROR = "DELAYING_ORDER_ERROR",
  FOK_ORDER_NOT_FILLED_ERROR = "FOK_ORDER_NOT_FILLED_ERROR",
  MARKET_NOT_READY = "MARKET_NOT_READY",
}
